# Generated by Django 4.2 on 2023-04-18 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("visualizer", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="company",
            table="companies",
        ),
        migrations.AlterModelTable(
            name="stockprice",
            table="stock_prices",
        ),
    ]
