# Generated by Django 4.2 on 2023-04-18 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("visualizer", "0002_alter_company_table_alter_stockprice_table"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Company",
        ),
        migrations.DeleteModel(
            name="StockPrice",
        ),
    ]
