# Generated by Django 4.2 on 2023-04-19 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visualizer", "0004_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockprice",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
